# mysql数据库连接
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: comic
    password: comic
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: lastwhisper-mybatis-plus
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

# 端口
server:
  port: 8080
