# mysql数据库连接
spring:
  datasource:
    url: jdbc:mysql://175.178.97.148:3306/comic?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: comic
    password: comic
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: lastwhisper-mybatis-plus

# 端口
server:
  port: 8080
